// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK-lKqJGQEeUDevbcTykm8Srr7sGv592Q',
    appId: '1:333653930292:web:c42665d4779eba256bb561',
    messagingSenderId: '333653930292',
    projectId: 'hoyaid-app-b2f66',
    authDomain: 'hoyaid-app-b2f66.firebaseapp.com',
    storageBucket: 'hoyaid-app-b2f66.firebasestorage.app',
    measurementId: 'G-RV37JVBM7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLoYnN1rGTqh8HEykcyQe0H7s-Dmht3IU',
    appId: '1:333653930292:android:714dc2390d07aa036bb561',
    messagingSenderId: '333653930292',
    projectId: 'hoyaid-app-b2f66',
    storageBucket: 'hoyaid-app-b2f66.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkUMeGsKp3Kt60-zglIt4ssAKRN-ebu5o',
    appId: '1:333653930292:ios:f884392dedd359216bb561',
    messagingSenderId: '333653930292',
    projectId: 'hoyaid-app-b2f66',
    storageBucket: 'hoyaid-app-b2f66.firebasestorage.app',
    androidClientId:
        '333653930292-dam4qqfhhhu7n47s787lk8fo0l6fapn5.apps.googleusercontent.com',
    iosClientId:
        '333653930292-jdec078va4g8n6aepkjes90dnrm819g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.taV1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkUMeGsKp3Kt60-zglIt4ssAKRN-ebu5o',
    appId: '1:333653930292:ios:f884392dedd359216bb561',
    messagingSenderId: '333653930292',
    projectId: 'hoyaid-app-b2f66',
    storageBucket: 'hoyaid-app-b2f66.firebasestorage.app',
    androidClientId:
        '333653930292-dam4qqfhhhu7n47s787lk8fo0l6fapn5.apps.googleusercontent.com',
    iosClientId:
        '333653930292-jdec078va4g8n6aepkjes90dnrm819g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.taV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK-lKqJGQEeUDevbcTykm8Srr7sGv592Q',
    appId: '1:333653930292:web:bf674dc2109ea99f6bb561',
    messagingSenderId: '333653930292',
    projectId: 'hoyaid-app-b2f66',
    authDomain: 'hoyaid-app-b2f66.firebaseapp.com',
    storageBucket: 'hoyaid-app-b2f66.firebasestorage.app',
    measurementId: 'G-LF13YGMQ1V',
  );
}
